### ISSUE TITLE
I can't run the project

### ISSUE THREAD

**Issue by salememd** [xuchong/android-opencv-ffmpeg#1]
Hi
I keep getting the following errors when I try to run the project
Error:error: '../../../../libs/x86/libopencv_java3.so', needed by '../../../../build/intermediates/cmake/debug/obj/x86/libnative-lib.so', missing and no known rule to make it
Error:org.gradle.internal.UncheckedException: Build command failed.
Error:error: '../../../../libs/x86/libopencv_java3.so', needed by '../../../../build/intermediates/cmake/debug/obj/x86/libnative-lib.so', missing and no known rule to make it
Error:Build command failed.
Error:error: '../../../../libs/x86/libopencv_java3.so', needed by '../../../../build/intermediates/cmake/debug/obj/x86/libnative-lib.so', missing and no known rule to make it

**Comment by xuchong** [comment]
@salememd The purpose of this project is using opencv with ffmpeg to read most type of videos. Moreover, i used cmake tool  so that you don't need to install opencv-manager on your android device which is not user-friendly. To achieve that， you need to firstly compile your  opencv source code with ffmpeg for android device( you will get lib files such as lib_opencv*.so/a, libswscale.so and so on including libopencv_java3.so which you lost).  Then, you compile your cpp code using cmake with your  opencv libs, you will get libnative-lib.so(the name depends on your CmakeLists.txt).  This project i didn't provide libs file so you need fetch them step by step according to  https://github.com/xuchong/android-opencv-ffmpeg#tutorials-3-steps.
