### ISSUE TITLE
The diff between official opencv4android and the compiled opencv4android in step 1

### ISSUE THREAD

**Issue by codeinmyself** [xuchong/android-opencv-ffmpeg#4]
On step 1, Can we just use the official opencv4android instead of the opencv4android compiled from source code by myself ?
（第一步中的opencv4Android编译是必要的吗，可以直接用官方的opencv4Android来完成第四步的内容吗）
And just a quick question, can you provide us with the results( .so/.a) since the process of compile seems too hard for me as a new to opencv ?
（可以提供编译好的成果作参考吗（armeabi-v7）^-^,感觉编译对我有点困难）

**Comment by xuchong** [comment]
I haven't tried the offical opencv4android. But i think that all versions ( opencv for android, iOS or windows) come from source code. You can compile your target from the source code. You will get any kind version of opencv with any module(such as ffmpeg, opencv-contrib). As far as I know, the offical opencv4android doesn't support ffmpeg. At the same time,  i want to know if the official opencv4android provides the android version source code? As i known, [the offical code](https://github.com/opencv/opencv/) doesn't have the special android branch.

At last,  step 1 just tells you how to complile opencv for android without ffmpeg. And step 4 is the final target. We start to do things step by step. Be patient , guys.  

The compiled libs will come soon.

**Comment by codeinmyself** [comment]
Thanks, where can we get the compiled libs ?

**Comment by xuchong** [comment]
Sorry guy, I was busy with my work this month. I haven’t prepared enough to share my libs in a good state. Deadline will be extended.

For helping you, I provide a temporary version of libs as follows:

Link: https://pan.baidu.com/s/1owcm0R9MSbsCB5XMvEouOQ  pwd: eqix

⚠️Attention：these libs are only for learning purpose. If you want to use it for others,  let me know.

Thank U.



在 2018年2月28日，下午8:18，codeinmyself <notifications@github.com<mailto:notifications@github.com>> 写道：


On step 2, Can we just use the official opencv4android instead of the opencv4android compiled from source code by myself ?
And just a quick question, can you provide us with the results( .so/.a) since the process of compile seems too hard for me as a new to opencv ?

**Comment by momo145** [comment]
楼主,你好,opencv我通过cmake编译通过了,也加上了ffmpeg交叉编译,但是VideoCapture传入视频一直是打开不了,我可以借用下你的so支持库吗? 但是你上面分享的网盘已经过期了,希望可以上传到github上,谢谢啦.可惜不能上传图片,不然可以让你看下我cmake上的 opencv so生成配置是否有误,可以指点一下.麻烦你了

**Comment by xuchong** [comment]
@momo145 link has already been updated.

**Comment by momo145** [comment]
@xuchong 楼主超厉害,可以打开文件了,然后我排除了一下我这边的问题,发现生成opencv+ffmpeg支持库是没问题的,关键是libopencv_java3.so没有生成,用了你的libopencv_java3.so就完美执行了,请问libopencv_java3是怎么生成的呢?再次感谢百忙之中给我们解答疑惑

**Comment by xuchong** [comment]
@momo145 when you compile opencv with ffmpeg, it should generate 'libopencv_java3.so'

**Comment by momo145** [comment]
@xuchong 已经生成成功了,但是你这边给的思路帮助很大,万分感谢,☺
